'use strict'
exports.Quiz = require('./Quiz')
exports.QuizQuestions = require('./QuizQuestions')
exports.QuizAnswers = require('./QuizAnswers')
exports.Roles = require('./Roles')
exports.Users = require('./Users')
exports.AttemptedQuizsAnswer = require('./AttemptedQuizsAnswer')
exports.AttemptedQuizs = require('./AttemptedQuizs')
exports.QualifiedQuizs = require('./QualifiedQuizs')
exports.QuizsMap = require('./QuizsMap')
